spring:
  application:
    name: analytics
spring.jpa:
  database: POSTGRESQL
  hibernate.ddl-auto: create
  show-sql: true

spring.datasource:
  platform: postgres
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/analytics
  username: postgres
  password: root
